### ISSUE TITLE
Perlin Noise

### ISSUE THREAD

**Issue by andrearastelli** [raytracingDevTeam/raytracing#21]

**Comment by andrearastelli** [comment]
@Ale32, I started working on this, based on the assumption that you will use a `texture.h` file for the texture class.
Also, I guess that the `Vec3` that is used in `Texture` and `Perlin` and all the other texture-related objects, should instead be our `Color` class.

branch name: `feature/perlin-noise` if you are interested.

**Comment by andrearastelli** [comment]
https://github.com/raytracingDevTeam/raytracing/tree/feature/perlin-noise

**Comment by Ale32** [comment]
Yes, I'll create that class in `texture.h` and I'll use `Color` instead of `Vec3`!

**Comment by andrearastelli** [comment]
![test_small_32](https://user-images.githubusercontent.com/675471/40469251-c71c484a-5f27-11e8-83c6-0c6e09b0d9bf.png)
