### ISSUE TITLE
Rectangles and Lights

### ISSUE THREAD

**Issue by andrearastelli** [raytracingDevTeam/raytracing#23]

**Comment by andrearastelli** [comment]
@Ale32 do you want to go and try this, or the `Instances` one?

**Comment by Ale32** [comment]
I'm going with this!

**Comment by andrearastelli** [comment]
Let's do this:
# I'm going with the Rectangle class, so that I can test the Instancing system
# As soon as the PR is approved you can start from that one and go with the Lights

What do you think?

**Comment by Ale32** [comment]
It's fine!
