### ISSUE TITLE
SIMD - Conversion of the Vec class for using SIMD operations

### ISSUE THREAD

**Issue by andrearastelli** [raytracingDevTeam/raytracing#64]
### SIMD
**S**ingle **I**nstruction **M**ultiple **D**ata. With this kind of operation set we should be able to parallelise all the operations in the Vec class so that we can use the multiple registry that every new and modern processor have.

> Without this, our processor is basically using only one calculation unit over 4 or multiple available for every instruction.
> So, for example, if we have a Vec class with `X`, `Y` and `Z`, we can do the normal calculations with every instruction after the other, or we can "load" the values of `x, y, z` into the SIMD "memory" (is a registry) and let the SIMD registry execute the operations in parallel.

For example, instead of doing:
```C++
Vec sum(const Vec &a, const Vec &b)
{
    Vec result(0, 0, 0);

    result.x = a.x + b.x;
    result.y = a.y + b.y;
    result.z = a.z + b.z;

    return result;
}
```

We can have something like this:
```C++
Vec sum(const Vec &a, const Vec &b)
{
    Vec result(0, 0, 0);

    simd_sum(result.simd_data, a.simd_data + b.simd_data);

    return result;
}
```

The "magic" function `simd_sum` is the one that will take care of loading the simd_data, doing the sum for every pair of values in both `a` and `b`, and store into `result.simd_data` the result of the operation.

> This is an oversemplification of the SIMD instruction set, but the idea is to use all the swimlanes available in the processor, instead of only doing calculation in one and let the other 3 or so do nothing.

- [StackOverflow SIMD conversation](https://stackoverflow.com/a/10851231/1162467)

**Comment by Ale32** [comment]
It sounds great! I don't know anything about SIMD, but it looks like is the right direction to proceed. I'll take a closer look.

**Comment by andrearastelli** [comment]
The code now works, and is so much faster than before...
Need to run some proper profiling to use specific numbers for comparison, but the feeling is that the raytracer is more than 3 times faster than before.

**Comment by Ale32** [comment]
I can't make it works on windows!

Anyway, I found this http://sci.tuomastonteri.fi/programming/sse, seems to be very useful!

**Comment by andrearastelli** [comment]
Very interesting: https://blog.demofox.org/2016/12/06/the-secret-to-writing-fast-code-how-fast-code-gets-slow/

**Comment by andrearastelli** [comment]
Ported also Color to be SIMD - this way we have another 2% of improvement in out codebase (from 50s to 49s to render a 800x800px image with 8 samples and 20 bounces).

**Comment by andrearastelli** [comment]
List of useful SIMD header linked to the hardware type:
https://stackoverflow.com/a/11228864/1162467

**Comment by andrearastelli** [comment]
@Ale32 I've updated all the `feature/SIMD-vec3` branch and now everything should compile and run on both Linux and Windows.

As soon as you can test it, please let me know if everything works even for you, locally, and approve the PR #66 .

I guess this can be considered the very last PR for Version 2.0.0, and every other improvements should be flagged as V3.

**Comment by andrearastelli** [comment]
@Ale32 both #65 and #66 now successfully pass all the tests on both Linux and Windows.
